In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random

fake = Faker('es_ES')

In [2]:
# empty dataframe

df = pd.DataFrame()

In [3]:
# create column "vehiculo_id"

df['vehiculo_id'] = range(1, 1001)

In [4]:
# create column "nombre_conductor"

df['nombre_conductor'] = [fake.name() for _ in range(len(df))]

In [5]:
# create column "conductor_id"

df['conductor_id'] = list(range(1000, 0, -1))

random.shuffle(df['conductor_id'])

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\random.py:383: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i], x[j] = x[j], x[i]

In [6]:
# create column "DNI"

df['dni_conductor'] = [str(fake.unique.random_number(digits=8)) + random.choice('TRWAGMYFPDXBNJZSQVHLCKE') for _ in range(len(df))]

In [7]:
import pandas as pd
import random

mcoches = ['Toyota', 'Honda', 'Ford', 'Chevrolet', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Nissan', 'Hyundai', 'Kia', 'Mazda', 'Volvo', 'Tesla', 'Porsche', 'Subaru', 'Jeep', 'Fiat', 'Jaguar', 'Land Rover', 'Lexus', 'MINI', 'Alfa Romeo', 'Mitsubishi', 'Buick', 'Cadillac', 'Chrysler', 'Dodge', 'Ram', 'GMC', 'Acura', 'Infiniti', 'Lincoln', 'Bentley', 'Bugatti', 'Ferrari', 'Lamborghini', 'Maserati', 'McLaren', 'Rolls-Royce']

probabilidades = {
    'Toyota': 0.12,
    'Honda': 0.1,
    'Ford': 0.1,
    'Chevrolet': 0.08,
    'Volkswagen': 0.08,
    'BMW': 0.07,
    'Mercedes-Benz': 0.06,
    'Audi': 0.05,
    'Nissan': 0.05,
    'Hyundai': 0.04,
    'Kia': 0.04,
    'Mazda': 0.03,
    'Volvo': 0.03,
    'Tesla': 0.02,
    'Porsche': 0.02,
    'Subaru': 0.02,
    'Jeep': 0.02,
    'Fiat': 0.01,
    'Jaguar': 0.01,
    'Land Rover': 0.01,
    'Lexus': 0.01,
    'MINI': 0.01,
    'Alfa Romeo': 0.01,
    'Mitsubishi': 0.01,
    'Buick': 0.008,
    'Cadillac': 0.008,
    'Chrysler': 0.008,
    'Dodge': 0.008,
    'Ram': 0.008,
    'GMC': 0.008,
    'Acura': 0.007,
    'Infiniti': 0.007,
    'Lincoln': 0.006,
    'Bentley': 0.002,
    'Bugatti': 0.001,
    'Ferrari': 0.001,
    'Lamborghini': 0.001,
    'Maserati': 0.001,
    'McLaren': 0.001,
    'Rolls-Royce': 0.001,
}

df = pd.DataFrame()
df['marca_coche'] = [random.choices(mcoches, weights=[probabilidades[marca] for marca in mcoches])[0] for _ in range(1000)]

In [8]:
# Create column "Color Coche"

df['color_coche'] = [fake.color_name() for _ in range(len(df))]

In [9]:
# Create column "Año Coche"

# Create column "Año Coche"

mapa_anios = {
    'Toyota': (2000, 2023),
    'Honda': (2000, 2023),
    'Ford': (2000, 2023),
    'Chevrolet': (2000, 2023),
    'Volkswagen': (2000, 2023),
    'BMW': (2000, 2023),
    'Mercedes-Benz': (2000, 2023),
    'Audi': (2000, 2023),
    'Nissan': (2000, 2023),
    'Hyundai': (2000, 2023),
    'Kia': (2000, 2023),
    'Mazda': (2000, 2023),
    'Volvo': (2000, 2023),
    'Tesla': (2009, 2023),  
    'Porsche': (2000, 2023),
    'Subaru': (2000, 2023),
    'Jeep': (2000, 2023),
    'Fiat': (2000, 2023),
    'Jaguar': (2000, 2023),
    'Land Rover': (2000, 2023),
    'Lexus': (2000, 2023),
    'MINI': (2000, 2023),
    'Alfa Romeo': (2000, 2023),
    'Mitsubishi': (2000, 2023),
    'Buick': (2000, 2023),
    'Cadillac': (2000, 2023),
    'Chrysler': (2000, 2023),
    'Dodge': (2000, 2023),
    'Ram': (2000, 2023),
    'GMC': (2000, 2023),
    'Acura': (2000, 2023),
    'Infiniti': (2000, 2023),
    'Lincoln': (2000, 2023),
    'Bentley': (2000, 2023),
    'Bugatti': (2000, 2023),
    'Ferrari': (2000, 2023),
    'Lamborghini': (2000, 2023),
    'Maserati': (2000, 2023),
    'McLaren': (2000, 2023),
    'Rolls-Royce': (2000, 2023),
}

probabilidades_anios = {
    anio: 1 / (2023 - anio + 1) ** 1.5 for anio in range(1990, 2024)
}

df['anio_fabricacion'] = [
    random.choices(
        range(*mapa_anios[marca]),
        weights=[probabilidades_anios[anio] for anio in range(*mapa_anios[marca])],
        k=1
    )[0]
    for marca in df['marca_coche']
]

In [10]:
# Create column "Tipo Combustible"

mapa_combustible = {
    'Tesla': 'Eléctrico',
    'Toyota': 'Híbrido',
    'Honda': 'Híbrido',
    'Nissan': 'Eléctrico',
    'BMW': 'Eléctrico o Híbrido',
    'Mercedes-Benz': 'Híbrido',
    'Audi': 'Eléctrico o Híbrido',
    'Lexus': 'Híbrido',
    'Porsche': 'Híbrido',
    'Chevrolet': 'Gasolina',
    'Ford': 'Gasolina',
    'Volkswagen': 'Gasolina',
    'Hyundai': 'Híbrido',
    'Kia': 'Híbrido',
    'Mazda': 'Gasolina',
    'Volvo': 'Híbrido o Eléctrico',
    'Subaru': 'Gasolina',
    'Jeep': 'Gasolina',
    'Fiat': 'Gasolina',
    'Jaguar': 'Eléctrico o Híbrido',
    'Land Rover': 'Gasolina',
    'Lexus': 'Híbrido',
    'MINI': 'Gasolina',
    'Alfa Romeo': 'Gasolina',
    'Mitsubishi': 'Gasolina',
    'Buick': 'Gasolina',
    'Cadillac': 'Gasolina',
    'Chrysler': 'Gasolina',
    'Dodge': 'Gasolina',
    'Ram': 'Gasolina',
    'GMC': 'Gasolina',
    'Acura': 'Gasolina',
    'Infiniti': 'Gasolina',
    'Lincoln': 'Gasolina',
    'Bentley': 'Gasolina',
    'Bugatti': 'Gasolina',
    'Ferrari': 'Gasolina',
    'Lamborghini': 'Gasolina',
    'Maserati': 'Gasolina',
    'McLaren': 'Gasolina',
    'Rolls-Royce': 'Gasolina',
}

df['tipo_combustible'] = df['marca_coche'].map(mapa_combustible)

porcentaje_cambio = 20 

marcas_multicombustible = df[df['tipo_combustible'].str.contains(' o ')]['marca_coche'].unique()
for marca in marcas_multicombustible:
    tipos = mapa_combustible[marca].split(' o ')
    if random.randint(0, 100) < porcentaje_cambio:
        df.loc[df['marca_coche'] == marca, 'tipo_combustible'] = random.choice(tipos)

df['tipo_combustible'] = df['tipo_combustible'].apply(lambda x: random.choice(x.split(' o ')) if ' o ' in x else x)

In [11]:
# Create column "Año Registro"

df['anio_registro_app'] = [random.randint(anio_fabricacion, 2023) for anio_fabricacion in df['anio_fabricacion']]

In [12]:
# Create column "Calefaccion"

probabilidades_calefaccion = {
    'Toyota': 0.2,
    'Honda': 0.3,
    'Ford': 0.4,
    'Chevrolet': 0.4,
    'Volkswagen': 0.4,
    'BMW': 0.8,
    'Mercedes-Benz': 0.9,
    'Audi': 0.8,
    'Nissan': 0.3,
    'Hyundai': 0.5,
    'Kia': 0.5,
    'Mazda': 0.3,
    'Volvo': 0.8,
    'Tesla': 0.9,
    'Porsche': 0.9,
    'Subaru': 0.4,
    'Jeep': 0.6,
    'Fiat': 0.3,
    'Jaguar': 0.8,
    'Land Rover': 0.9,
    'Lexus': 0.7,
    'MINI': 0.5,
    'Alfa Romeo': 0.7,
    'Mitsubishi': 0.4,
    'Buick': 0.6,
    'Cadillac': 0.7,
    'Chrysler': 0.4,
    'Dodge': 0.5,
    'Ram': 0.6,
    'GMC': 0.6,
    'Acura': 0.7,
    'Infiniti': 0.7,
    'Lincoln': 0.6,
    'Bentley': 0.9,
    'Bugatti': 0.9,
    'Ferrari': 0.9,
    'Lamborghini': 0.9,
    'Maserati': 0.8,
    'McLaren': 0.8,
    'Rolls-Royce': 0.9,
    'Smart': 0.2
}

df['tiene_calefaccion'] = [random.choices([True, False], [prob, 1 - prob], k=1)[0] for prob in df['marca_coche'].map(probabilidades_calefaccion)]

In [13]:
# create column "Puntos Carnet"

probabilidades_puntos = {
    15: 0.15,
    14: 0.11,
    13: 0.1,
    12: 0.1,
    11: 0.1,
    10: 0.06,
    9: 0.06,
    8: 0.06,
    7: 0.06,
    6: 0.06,
    5: 0.05,
    4: 0.04,
    3: 0.03,
    2: 0.02,
    1: 0.01
}

df['puntos_carnet'] = [random.choices(list(probabilidades_puntos.keys()), list(probabilidades_puntos.values()), k=1)[0] for _ in range(len(df))]

In [14]:
# create column "cilndraje motor"

cilindrajes_por_marca = {
    'Toyota': [1200, 1500, 1800, 2500],
    'Honda': [1300, 1600, 2000, 2500],
    'Ford': [1500, 2000, 2500, 3000],
    'Chevrolet': [1400, 1800, 2200, 3000],
    'Volkswagen': [1200, 1600, 2000, 2500],
    'BMW': [1600, 2000, 2500, 3000],
    'Mercedes-Benz': [1800, 2200, 2500, 3000],
    'Audi': [1600, 2000, 2500, 3000],
    'Nissan': [1200, 1500, 1800, 2500],
    'Hyundai': [1200, 1500, 1800, 2500],
    'Kia': [1300, 1600, 2000, 2500],
    'Mazda': [1200, 1500, 1800, 2500],
    'Volvo': [1800, 2200, 2500, 3000],
    'Tesla': [0],
    'Porsche': [2500, 3000, 3500, 4000],
    'Subaru': [1500, 1800, 2000, 2500],
    'Jeep': [1800, 2200, 2500, 3000],
    'Fiat': [1200, 1400, 1600, 2000],
    'Jaguar': [1800, 2200, 2500, 3000],
    'Land Rover': [1800, 2200, 2500, 3000],
    'Lexus': [2000, 2500, 3000, 3500],
    'MINI': [1200, 1400, 1600, 2000],
    'Alfa Romeo': [1600, 1800, 2000, 2500],
    'Mitsubishi': [1200, 1500, 1800, 2500],
    'Buick': [1800, 2000, 2500, 3000],
    'Cadillac': [2000, 2500, 3000, 3500],
    'Chrysler': [1800, 2000, 2500, 3000],
    'Dodge': [2000, 2500, 3000, 3500],
    'Ram': [2000, 2500, 3000, 3500],
    'GMC': [2000, 2500, 3000, 3500],
    'Acura': [1600, 2000, 2500, 3000],
    'Infiniti': [2000, 2500, 3000, 3500],
    'Lincoln': [2000, 2500, 3000, 3500],
    'Bentley': [4000, 5000, 6000, 7000],
    'Bugatti': [6000, 8000, 10000, 12000],
    'Ferrari': [4000, 5000, 6000, 7000],
    'Lamborghini': [5000, 6000, 7000, 8000],
    'Maserati': [3000, 4000, 5000, 6000],
    'McLaren': [4000, 5000, 6000, 7000],
    'Rolls-Royce': [4000, 5000, 6000, 7000],
}

df['cilindraje_motor'] = [random.choice(cilindrajes_por_marca[marca]) if tipo in ('Gasolina', 'Híbrido') else 0 for marca, tipo in zip(df['marca_coche'], df['tipo_combustible'])]

In [15]:
def calcular_kilometraje(anio_fabricacion):
    anios_actuales = 2023
    desgaste_anual = 15000 

    kilometraje_base = (anios_actuales - anio_fabricacion) * desgaste_anual

    return random.randint(int(0.8 * kilometraje_base), int(1.2 * kilometraje_base))


df['kilometraje'] = [calcular_kilometraje(anio) for anio in df['anio_fabricacion']]

In [16]:
df.head()

,vehiculo_id,nombre_conductor,conductor_id,dni_conductor,marca_coche,color_coche,anio_fabricacion,tipo_combustible,anio_registro_app,tiene_calefaccion,puntos_carnet,cilindraje_motor,kilometraje
0,1,Hector del Donoso,943,56142213N,Cadillac,Azul acero claro,2022,Gasolina,2022,False,15,3000,15409
1,2,Paco Vera Soriano,661,1671481E,Fiat,Marrón arena,2022,Gasolina,2023,False,15,1200,15956
2,3,Nilda Aroca,100,79574279P,Subaru,Almendra blanqueado,2002,Gasolina,2004,False,13,2000,278511
3,4,Albano Armas Beltrán,168,52717721K,Mercedes-Benz,Verde prado,2016,Híbrido,2016,True,13,3000,88827
4,5,Curro Barón-Castejón,652,26391271F,Infiniti,Rojo,2006,Gasolina,2018,True,11,2000,242362

In [18]:
from google.cloud import bigquery

client = bigquery.Client()

df.to_gbq('BBDD.tabla_vehiculos', project_id='dataproject-2-413010', if_exists='replace')

100%|██████████| 1/1 [00:00<?, ?it/s]